sudo: required
services:
  - docker

before_install:
  - docker build -t fibonnaci -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true fibonacci npm test

after_success:
  - docker build -t fibonnaci-client ./client
  - docker build -t fibonnaci-nginx ./nginx
  - docker build -t fibonnaci-server ./server
  - docker build -t fibonnaci-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push to docker hub
  - docker push fibonnaci-client
  - docker push fibonnaci-nginx
  - docker push fibonnaci-server
  - docker push fibonnaci-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "docker-react"
#  env: "DockerReact-env"
#  bucket_name: "elasticbeanstalk-us-east-2-901399634517"
#  bukect_path: "docker-react"
#  on:
#    branch: master
#  access_key_id:
#    secure: "$AWS_ACCESS_KEY"
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"